#!/bin/bash

#### t-drop
#############################################################################
#                t-drop        ./scripts/commands/table/t-drop              #
#  script used to  drop a table from a given data base.                     #
#  authors: github.com/hadilotfy , github.com/Mustafa-Essam223              #
#                                                                           #
#  >>> interfacing                                                          #
#  """""""""""""""                                                          #
#        $$$ t-drop <db-fname>    :  ask user to input table name           #
# postponed $$$ t-drop <t-name> from <db-fname>     : delete directly       #
#                                                                           #
#   * any additional argument will be ignored                               #
#############################################################################


db_fname=$1

echo "t-drop: Table list:"
ls $db_fname
printf "t-drop: Which table to drop: "
read t_name

t_fname="$db_fname/$t_name"
if [ -f $t_fname ] ;then
    rm $t_fname
else
    echo "t-drop: Table $t_name does not exist!"
fi


exit

t_name=$(echo $t_fname | rev | cut -d/ -f1 | rev) #table 

ls $t_fname 
rm $t_fname
echo "t-drop: table ($t_name) deleted successfully!"
