#!/bin/bash


#### db-drop
#############################################################################
#                db-drop      path: ./scripts/commands/database/db-drop     #
#  script used to drop the whole of a database from the specified directory #
#  and from the default directory if path not specified                     #
# authors: github.com/hadilotfy , github.com/Mustafa-Essam223               #
#                                                                           #
#  >>> interfacing                                                          #
#  """""""""""""""                                                          #
#        $$$ [dbms] db-drop <db-name> [<path>]                              #
#           : drop db with name <db-name> in <path> is specified and        #
#             in the path named (data_path) in  (config) file if not        #
#             specified.                                                    #
#                                                                           #
#   * any additional argument will be ignored                               #
#############################################################################

data_path='./data'

if [ $# -eq 0  ]
then
    echo "db-drop: menu"
    read -p "db-drop: Enter DB name: " db_name
    read -p "db-drop: Enter DB path(press enter for default): " db_path
   # note the symbol (~) is not replaced with home dir but considerd relative.
   # so a directory named ~ has been made in $PWD
else
    db_path=$2
    db_name=$1
fi

    # use the second arg. if present as the path to data
    if [ $db_path ]; then data_path=$db_path; fi

    # use first argument as db name
    db_fname=$data_path/$db_name
    echo $db_fname
    # check if the db exists already if so exit with code 1001
    if [ -d $db_fname  ]
    then
        # already there is a db with this name
        count=`ls $db_fname | wc -l`
        if [ $count -ne 0 ]
        then read -p 'db not empty! sure to drop it? y/Y : '  -n 1
            echo ""
            if [[ ! $REPLY =~ ^[yY] ]] ; then exit 1003 ; fi
        fi
        rm -r $db_fname


    else #
        # No such db in such path.
        echo "db-drop: DataBase ($db_fname) is not found."
        exit 1002
    fi


