#!/bin/bash

#############################################################################
#                       db-list                                             #
#  script used to list databases stored @                                   #
#                    $ProjectPath/scripts/data                              #
#                                                                           #
#  authors: github.com/hadilotfy , github.com/Mustafa-Essam223              #
#                                                                           #
#############################################################################
ProjectPath='/home/hadi/iti3m/06_Shell_Scripting/Bash_Project'


echo "Database List"
read -n1 -p "check if specific database exists? [y/n]: " ans
if [ "$ans" = "Y" ] || [ "$ans" = "y" ]
then 
    echo ""
    read -p "enter a database name: " name

	if [ "$name" == "" ]
	then 
	    echo "not a valid name !!!!!!!!!!!!!!!!!!!!!!"
	
	elif [ -d $ProjectPath/scripts/data/$name ] #&& [ "$name" != "" ]
	then 
	    echo "Exists"
	
	else
	    echo "not exists!"
	fi
		
else 
	echo ""
	echo "All Databases **"
	ls "$ProjectPath/scripts/data"
fi 









